//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPSLSFrontend.RPSLS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PlayAttempt", Namespace="http://schemas.datacontract.org/2004/07/RPSLSService")]
    [System.SerializableAttribute()]
    public partial class PlayAttempt : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RPSLSFrontend.RPSLS.Symbols ComputerSymbolField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PlayerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private RPSLSFrontend.RPSLS.Symbols PlayerSymbolField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WinnerField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RPSLSFrontend.RPSLS.Symbols ComputerSymbol {
            get {
                return this.ComputerSymbolField;
            }
            set {
                if ((this.ComputerSymbolField.Equals(value) != true)) {
                    this.ComputerSymbolField = value;
                    this.RaisePropertyChanged("ComputerSymbol");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateTime {
            get {
                return this.DateTimeField;
            }
            set {
                if ((this.DateTimeField.Equals(value) != true)) {
                    this.DateTimeField = value;
                    this.RaisePropertyChanged("DateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PlayerName {
            get {
                return this.PlayerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PlayerNameField, value) != true)) {
                    this.PlayerNameField = value;
                    this.RaisePropertyChanged("PlayerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public RPSLSFrontend.RPSLS.Symbols PlayerSymbol {
            get {
                return this.PlayerSymbolField;
            }
            set {
                if ((this.PlayerSymbolField.Equals(value) != true)) {
                    this.PlayerSymbolField = value;
                    this.RaisePropertyChanged("PlayerSymbol");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Winner {
            get {
                return this.WinnerField;
            }
            set {
                if ((object.ReferenceEquals(this.WinnerField, value) != true)) {
                    this.WinnerField = value;
                    this.RaisePropertyChanged("Winner");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Symbols", Namespace="http://schemas.datacontract.org/2004/07/RPSLSService")]
    public enum Symbols : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Rock = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Paper = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Scissor = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Lizard = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Spock = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Empty = 5,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RPSLS.IService")]
    public interface IService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DoPlay", ReplyAction="http://tempuri.org/IService/DoPlayResponse")]
        RPSLSFrontend.RPSLS.PlayAttempt DoPlay(RPSLSFrontend.RPSLS.PlayAttempt value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService/DoPlay", ReplyAction="http://tempuri.org/IService/DoPlayResponse")]
        System.Threading.Tasks.Task<RPSLSFrontend.RPSLS.PlayAttempt> DoPlayAsync(RPSLSFrontend.RPSLS.PlayAttempt value);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceChannel : RPSLSFrontend.RPSLS.IService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceClient : System.ServiceModel.ClientBase<RPSLSFrontend.RPSLS.IService>, RPSLSFrontend.RPSLS.IService {
        
        public ServiceClient() {
        }
        
        public ServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public RPSLSFrontend.RPSLS.PlayAttempt DoPlay(RPSLSFrontend.RPSLS.PlayAttempt value) {
            return base.Channel.DoPlay(value);
        }
        
        public System.Threading.Tasks.Task<RPSLSFrontend.RPSLS.PlayAttempt> DoPlayAsync(RPSLSFrontend.RPSLS.PlayAttempt value) {
            return base.Channel.DoPlayAsync(value);
        }
    }
}
